name: Build stockfish-socket-server Docker image

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "main"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the stockfish-socket-server Docker image
      run: docker build . --file Dockerfile --tag stockfish-socket-server:latest
